function task_gen_visual_theme_d3(query, ...
				  root_path, ...
				  tag_dim, ...
				  cca_feature_dim, ...
				  num_clusters)
    addpath('../cca');
    config = gen_iconic_config_data(query, ...
				  root_path, ...
				  tag_dim, ...
				  cca_feature_dim, ...
				  num_clusters)


    cca_feature_dim = config.cca_feature_dim(1);
    current_result_name = sprintf('result_%d_%s', cca_feature_dim, config.iconic_result_id);
    iconic_path = sprintf('%s/%s.mat', config.iconic_result_output_root, current_result_name)

    clusters = config.database.get_iconic_clusters(iconic_path);

    visual_theme_generator_d3(config.web_page_output_root, ...
			      sprintf('%s_visual_theme', config.iconic_result_id), ...
			      clusters, ...
			      config.database, ...
			      config, ...
			      1);

    visual_theme_generator_d3(config.web_page_output_root, ...
			      config.iconic_result_id, ...
			      clusters, ...
			      config.database, ...
			      config, ...
			      0);


    exit();
end
